language: android
jdk: oraclejdk8
sudo: false

if: type == pull_request OR tag IS present

env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3

android:
  components:
  - tools
  - platform-tools
  - android-$ANDROID_API_LEVEL
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION

licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

before_install:
- yes | sdkmanager "platforms;android-28"

after_failure:
- cat $TRAVIS_BUILD_DIR/app/build/reports/lint-results.xml

stages:
- name: tests
- name: compile-uikit
- name: compile-modules
- name: compile-samples
- name: deploy
  if: tag =~ ^\d+\.\d+\.\d+$

jobs:
  include:
  - stage: tests #todo UI tests!
    script:
    - ./gradlew check -P"sygic.sdk.key"=$SYGIC_API_KEY #todo run parallel tests by module?
  - stage: compile-uikit
    script:
    - ./gradlew :uikit-common:build
    - ./gradlew :uikit-common-sdk:build
    - ./gradlew :uikit-compass:build
    - ./gradlew :uikit-compass-viewmodel:build
    - ./gradlew :uikit-poidetail:build
    - ./gradlew :uikit-positionlockfab:build
    - ./gradlew :uikit-positionlockfab-viewmodel:build
    - ./gradlew :uikit-zoomcontrols:build
    - ./gradlew :uikit-zoomcontrols-viewmodel:build
  - stage: compile-modules
    script:
    - ./gradlew :modules-common:build
    - ./gradlew :modules-browsemap:build
  - stage: compile-samples
    script:
    - ./gradlew :app-samples:build
  - stage: deploy
    script:
    - ./gradlew assembleRelease -P"sygic.sdk.key"=$SYGIC_API_KEY #todo credentials?
    deploy:
      provider: script #todo provider: releases
      script: echo 'deploing job done' #todo real deploy ;)
      file: $TRAVIS_BUILD_DIR/app/samples/build/outputs/apk/release/app-samples-arm64-v8a-release.apk
      skip_cleanup: true
    after_deploy:
    - rm -rf $TRAVIS_BUILD_DIR/app/samples/build/outputs
